name: Basic tests
on:
 push:
   paths:
   - 'env.yml'
 workflow_dispatch:
 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
         environment-file: env.yaml
   
